import httpx
import time
from config import config

# Cost per 1M tokens (Input, Output) in USD
PRICING_TABLE = {
    "anthropic/claude-3-5-sonnet": {"input": 3.00, "output": 15.00, "display": "Claude 3.5 Sonnet"},
    "openai/gpt-4o": {"input": 5.00, "output": 15.00, "display": "GPT-4o"},
    "openai/gpt-4o-mini": {"input": 0.150, "output": 0.600, "display": "GPT-4o Mini"},
    "google/gemini-2.5-flash": {"input": 0.075, "output": 0.300, "display": "Gemini 2.5 Flash"},
    "ollama/llama3": {"input": 0.00, "output": 0.00, "display": "Llama 3 (Local)"}
}

class LLMProviderService:
    def __init__(self):
        # We can dynamically configure actual clients if keys are provided
        self.openai_key = config.OPENAI_API_KEY
        self.anthropic_key = config.ANTHROPIC_API_KEY
        self.gemini_key = config.GEMINI_API_KEY
        self.ollama_url = config.OLLAMA_BASE_URL
        
    def calculate_cost(self, model_key: str, input_tokens: int, output_tokens: int) -> float:
        pricing = PRICING_TABLE.get(model_key, {"input": 0.0, "output": 0.0})
        cost_input = (input_tokens / 1_000_000) * pricing["input"]
        cost_output = (output_tokens / 1_000_000) * pricing["output"]
        return round(cost_input + cost_output, 6)

    async def execute_request(self, model_key: str, prompt: str, system_prompt: str = None) -> dict:
        """
        Executes a real LLM request or falls back to highly realistic simulated answers
        if the API keys are missing or mock mode is forced.
        """
        is_mock = config.is_mock_mode
        start_time = time.time()
        
        # Parse model and provider
        parts = model_key.split('/')
        provider = parts[0]
        model = parts[1] if len(parts) > 1 else model_key
        
        # If not mock, execute real request
        if not is_mock:
            try:
                if provider == "openai":
                    return await self._call_openai(model, prompt, system_prompt, start_time)
                elif provider == "anthropic":
                    return await self._call_anthropic(model, prompt, system_prompt, start_time)
                elif provider == "google":
                    return await self._call_gemini(model, prompt, system_prompt, start_time)
                elif provider == "ollama":
                    return await self._call_ollama(model, prompt, system_prompt, start_time)
            except Exception as e:
                # Let the routing logic handle failover
                raise e

        # SIMULATED RESPONSE ENGINE
        # Highly realistic, contextual responses based on prompt keywords to show full dashboard capability!
        time.sleep(0.4 + (0.3 if "sonnet" in model_key or "gpt-4o" == model else 0.1)) # Simulated latency
        latency_ms = int((time.time() - start_time) * 1000)
        
        # Generate responsive mock data
        response_text = self._generate_mock_response(model_key, prompt)
        prompt_tokens = len(prompt.split()) + 10
        completion_tokens = len(response_text.split()) + 15
        
        return {
            "text": response_text,
            "provider": provider,
            "actual_model": model_key,
            "latency_ms": latency_ms,
            "prompt_tokens": prompt_tokens,
            "completion_tokens": completion_tokens,
            "cost": self.calculate_cost(model_key, prompt_tokens, completion_tokens)
        }

    def _generate_mock_response(self, model_key: str, prompt: str) -> str:
        prompt_lower = prompt.lower()
        model_display = PRICING_TABLE.get(model_key, {}).get("display", model_key)
        
        if "hello" in prompt_lower or "hi " in prompt_lower:
            return f"Hello! This is a simulated response from **{model_display}** routed via **routerio**. How can I help you with your enterprise operations today?"
        
        if "sql" in prompt_lower or "query" in prompt_lower:
            return f"```sql\n-- Generated by {model_display} (routerio)\nSELECT user_id, COUNT(id) as total_requests, SUM(cost) as total_spent\nFROM api_logs\nWHERE timestamp >= datetime('now', '-30 days')\nGROUP BY user_id\nORDER BY total_spent DESC;\n```"
            
        if "code" in prompt_lower or "write a" in prompt_lower or "python" in prompt_lower:
            return f"```python\n# Created with {model_display} (routerio gateway)\nimport httpx\n\ndef call_router_endpoint(prompt: str, policy: str = 'cost'):\n    url = 'http://localhost:8000/v1/chat/completions'\n    headers = {{'Authorization': 'Bearer routerio_poc_key_2026'}}\n    payload = {{\n        'messages': [{{'role': 'user', 'content': prompt}}],\n        'model': 'routerio-intelligent-router',\n        'policy': policy\n    }}\n    response = httpx.post(url, json=payload, headers=headers)\n    return response.json()\n```"
            
        return f"Here is your analyzed result processed by **{model_display}** under the requested routing rules.\n\n**Analysis Details:**\n1. Input Length: {len(prompt)} characters\n2. Engine Priority: Dynamic balancing protocol activated\n3. Routing Layer: `routerio v1.0.0` gateway validation passed.\n\nHow else can I assist in optimizing your multi-vendor workflows?"

    # Upstream integration stubs
    async def _call_openai(self, model: str, prompt: str, system_prompt: str, start_time: float) -> dict:
        import openai
        # Standard async call setup
        client = openai.AsyncOpenAI(api_key=self.openai_key)
        messages = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": prompt})
        
        response = await client.chat.completions.create(
            model=model,
            messages=messages,
            timeout=15.0
        )
        latency_ms = int((time.time() - start_time) * 1000)
        p_tokens = response.usage.prompt_tokens
        c_tokens = response.usage.completion_tokens
        model_key = f"openai/{model}"
        
        return {
            "text": response.choices[0].message.content,
            "provider": "openai",
            "actual_model": model_key,
            "latency_ms": latency_ms,
            "prompt_tokens": p_tokens,
            "completion_tokens": c_tokens,
            "cost": self.calculate_cost(model_key, p_tokens, c_tokens)
        }

    async def _call_anthropic(self, model: str, prompt: str, system_prompt: str, start_time: float) -> dict:
        import anthropic
        client = anthropic.AsyncAnthropic(api_key=self.anthropic_key)
        system_arg = system_prompt if system_prompt else ""
        
        response = await client.messages.create(
            model=model,
            max_tokens=1024,
            system=system_arg,
            messages=[{"role": "user", "content": prompt}],
            timeout=15.0
        )
        latency_ms = int((time.time() - start_time) * 1000)
        p_tokens = response.usage.input_tokens
        c_tokens = response.usage.output_tokens
        model_key = f"anthropic/{model}"
        
        return {
            "text": response.content[0].text,
            "provider": "anthropic",
            "actual_model": model_key,
            "latency_ms": latency_ms,
            "prompt_tokens": p_tokens,
            "completion_tokens": c_tokens,
            "cost": self.calculate_cost(model_key, p_tokens, c_tokens)
        }

    async def _call_gemini(self, model: str, prompt: str, system_prompt: str, start_time: float) -> dict:
        # Standard Gemini API standard openai-compatible integration for speed and reliability
        import openai
        # Gemini provides standard openai endpoint compatibility as well
        client = openai.AsyncOpenAI(
            api_key=self.gemini_key,
            base_url="https://generativelanguage.googleapis.com/v1beta/openai/"
        )
        messages = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": prompt})
        
        # Normalize model names to standard google model tags
        gemini_model = "gemini-2.5-flash" if "flash" in model else model
        
        response = await client.chat.completions.create(
            model=gemini_model,
            messages=messages,
            timeout=15.0
        )
        latency_ms = int((time.time() - start_time) * 1000)
        p_tokens = response.usage.prompt_tokens
        c_tokens = response.usage.completion_tokens
        model_key = f"google/{model}"
        
        return {
            "text": response.choices[0].message.content,
            "provider": "google",
            "actual_model": model_key,
            "latency_ms": latency_ms,
            "prompt_tokens": p_tokens,
            "completion_tokens": c_tokens,
            "cost": self.calculate_cost(model_key, p_tokens, c_tokens)
        }

    async def _call_ollama(self, model: str, prompt: str, system_prompt: str, start_time: float) -> dict:
        async with httpx.AsyncClient() as client:
            payload = {
                "model": model,
                "messages": [],
                "stream": False
            }
            if system_prompt:
                payload["messages"].append({"role": "system", "content": system_prompt})
            payload["messages"].append({"role": "user", "content": prompt})
            
            response = await client.post(
                f"{self.ollama_url}/v1/chat/completions",
                json=payload,
                timeout=20.0
            )
            data = response.json()
            latency_ms = int((time.time() - start_time) * 1000)
            
            p_tokens = data.get("usage", {}).get("prompt_tokens", len(prompt.split()))
            c_tokens = data.get("usage", {}).get("completion_tokens", len(data["choices"][0]["message"]["content"].split()))
            model_key = f"ollama/{model}"
            
            return {
                "text": data["choices"][0]["message"]["content"],
                "provider": "ollama",
                "actual_model": model_key,
                "latency_ms": latency_ms,
                "prompt_tokens": p_tokens,
                "completion_tokens": c_tokens,
                "cost": 0.0
            }
